Add appropriate error to heater-set when wemo-cli is not present

diff --git a/bin/heater-set b/bin/heater-set
--- a/bin/heater-set
+++ b/bin/heater-set
@@ -21,6 +21,11 @@ make-request() {
   fi
 }
 
+if [[ ! -f ~/Projects/000_Others/matthewhuie-wemo-cli/wemo-cli ]]; then
+  echo "wemo-cli not found at: ~/Projects/000_Others/matthewhuie-wemo-cli/wemo-cli"
+  exit 1
+fi
+
 until [[ -f /tmp/heater-set-completed ]]; do
   make-request &
   sleep 0.5
